<a href="https://colab.research.google.com/github/saiprasadag20/STTP_on_ml/blob/main/saiann.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import*

In [ ]:
data=pd.read_csv("/content/breast_cancer _ day1.csv")

In [ ]:
data.head()

         id diagnosis  ...  symmetry_worst  fractal_dimension_worst
0    842302         M  ...          0.4601                  0.11890
1    842517         M  ...          0.2750                  0.08902
2  84300903         M  ...          0.3613                  0.08758
3  84348301         M  ...          0.6638                  0.17300
4  84358402         M  ...          0.2364                  0.07678

[5 rows x 32 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    object
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
dtypes: float64(30), int64(1), object(1)
memory usage: 142.4+ KB

In [ ]:
data=data.drop(['id'],axis=1)

In [ ]:
data.shape

(569, 31)

In [ ]:
x=data.drop(['diagnosis'],axis=1)

In [ ]:
x.shape

(569, 30)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(data['diagnosis'])

In [ ]:
y.shape

(569,)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
y=pd.DataFrame(y)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)

In [ ]:
x=pd.DataFrame(x)

In [ ]:
x.head()

         0         1         2   ...        27        28        29
0  1.097064 -2.073335  1.269934  ...  2.296076  2.750622  1.937015
1  1.829821 -0.353632  1.685955  ...  1.087084 -0.243890  0.281190
2  1.579888  0.456187  1.566503  ...  1.955000  1.152255  0.201391
3 -0.768909  0.253732 -0.592687  ...  2.175786  6.046041  4.935010
4  1.750297 -1.151816  1.776573  ...  0.729259 -0.868353 -0.397100

[5 rows x 30 columns]

In [ ]:
y.shape

(569, 1)

In [ ]:
from sklearn.model_selection import(train_test_split)
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=0)

In [ ]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(455, 30)
(114, 30)
(455, 1)
(114, 1)

In [ ]:
y.value_counts()

0
0    357
1    212
Name: count, dtype: int64

In [ ]:
y_train.value_counts()

0
0    290
1    165
Name: count, dtype: int64

In [ ]:
model=Sequential()

In [ ]:
model.add(Dense(16,input_dim=30,activation='relu'))
model.add(Dense(32,activation='relu'))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(x_train,y_train,epochs=50,validation_data=(x_test,y_test))

Epoch 1/50

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

15/15 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.4722 - loss: 0.6470 - val_accuracy: 0.7105 - val_loss: 0.5452
Epoch 2/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8200 - loss: 0.5228 - val_accuracy: 0.9123 - val_loss: 0.4427
Epoch 3/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9629 - loss: 0.4208 - val_accuracy: 0.9298 - val_loss: 0.3583
Epoch 4/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9611 - loss: 0.3350 - val_accuracy: 0.9211 - val_loss: 0.2844
Epoch 5/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9785 - loss: 0.2375 - val_accuracy: 0.9211 - val_loss: 0.2261
Epoch 6/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9591 - loss: 0.1813 - val_accuracy: 0.9211 - val_loss: 0.1880
Epoch 7/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9681 - loss: 0.1406 - val_accuracy: 0.9211 - val_loss: 0.1638
Epoch 8/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9675 - loss: 0.1219 - val_accuracy: 0.9211 - val_loss: 0.1500
Epoch 9/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9629 - loss: 0.1141 - val_accuracy: 0.9211 - val_loss: 0.1417
Epoch 10/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9721 - loss: 0.0947 - val_accuracy: 0.9298 - val_loss: 0.1358
Epoch 11/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9817 - loss: 0.0733 - val_accuracy: 0.9298 - val_loss: 0.1310
Epoch 12/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9849 - loss: 0.0700 - val_accuracy: 0.9474 - val_loss: 0.1273
Epoch 13/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9737 - loss: 0.0757 - val_accuracy: 0.9474 - val_loss: 0.1225
Epoch 14/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9845 - loss: 0.0611 - val_accuracy: 0.9474 - val_loss: 0.1183
Epoch 15/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9753 - loss: 0.0689 - val_accuracy: 0.9474 - val_loss: 0.1153
Epoch 16/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9777 - loss: 0.0725 - val_accuracy: 0.9561 - val_loss: 0.1124
Epoch 17/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9869 - loss: 0.0553 - val_accuracy: 0.9561 - val_loss: 0.1103
Epoch 18/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9793 - loss: 0.0628 - val_accuracy: 0.9561 - val_loss: 0.1088
Epoch 19/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9840 - loss: 0.0557 - val_accuracy: 0.9561 - val_loss: 0.1061
Epoch 20/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9873 - loss: 0.0447 - val_accuracy: 0.9561 - val_loss: 0.1033
Epoch 21/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9841 - loss: 0.0563 - val_accuracy: 0.9561 - val_loss: 0.1012
Epoch 22/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9900 - loss: 0.0507 - val_accuracy: 0.9561 - val_loss: 0.0993
Epoch 23/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9889 - loss: 0.0418 - val_accuracy: 0.9561 - val_loss: 0.0961
Epoch 24/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9893 - loss: 0.0371 - val_accuracy: 0.9561 - val_loss: 0.0945
Epoch 25/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9698 - loss: 0.0810 - val_accuracy: 0.9561 - val_loss: 0.0918
Epoch 26/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9903 - loss: 0.0401 - val_accuracy: 0.9561 - val_loss: 0.0904
Epoch 27/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9851 - loss: 0.0370 - val_accuracy: 0.9649 - val_loss: 0.0884
Epoch 28/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9895 - loss: 0.0407 - val_accuracy: 0.9649 - val_loss: 0.0879
Epoch 29/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9923 - loss: 0.0378 - val_accuracy: 0.9649 - val_loss: 0.0870
Epoch 30/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9842 - loss: 0.0434 - val_accuracy: 0.9649 - val_loss: 0.0859
Epoch 31/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9898 - loss: 0.0412 - val_accuracy: 0.9649 - val_loss: 0.0847
Epoch 32/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9856 - loss: 0.0485 - val_accuracy: 0.9649 - val_loss: 0.0840
Epoch 33/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9904 - loss: 0.0324 - val_accuracy: 0.9649 - val_loss: 0.0849
Epoch 34/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9905 - loss: 0.0359 - val_accuracy: 0.9649 - val_loss: 0.0849
Epoch 35/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9917 - loss: 0.0322 - val_accuracy: 0.9649 - val_loss: 0.0838
Epoch 36/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9919 - loss: 0.0319 - val_accuracy: 0.9649 - val_loss: 0.0835
Epoch 37/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9945 - loss: 0.0228 - val_accuracy: 0.9649 - val_loss: 0.0831
Epoch 38/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9931 - loss: 0.0298 - val_accuracy: 0.9649 - val_loss: 0.0827
Epoch 39/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9946 - loss: 0.0262 - val_accuracy: 0.9649 - val_loss: 0.0825
Epoch 40/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9916 - loss: 0.0281 - val_accuracy: 0.9737 - val_loss: 0.0830
Epoch 41/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9856 - loss: 0.0353 - val_accuracy: 0.9737 - val_loss: 0.0823
Epoch 42/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9930 - loss: 0.0248 - val_accuracy: 0.9737 - val_loss: 0.0825
Epoch 43/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9916 - loss: 0.0279 - val_accuracy: 0.9737 - val_loss: 0.0811
Epoch 44/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9848 - loss: 0.0392 - val_accuracy: 0.9737 - val_loss: 0.0808
Epoch 45/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9910 - loss: 0.0233 - val_accuracy: 0.9737 - val_loss: 0.0803
Epoch 46/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9919 - loss: 0.0208 - val_accuracy: 0.9737 - val_loss: 0.0782
Epoch 47/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9923 - loss: 0.0210 - val_accuracy: 0.9737 - val_loss: 0.0775
Epoch 48/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9932 - loss: 0.0225 - val_accuracy: 0.9737 - val_loss: 0.0774
Epoch 49/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9949 - loss: 0.0168 - val_accuracy: 0.9737 - val_loss: 0.0778
Epoch 50/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9933 - loss: 0.0188 - val_accuracy: 0.9737 - val_loss: 0.0794

In [ ]:
ypred=model.predict(x_test)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step

In [ ]:
ypred.shape

(114, 1)

In [ ]:
y_test

     0
512  1
457  0
439  0
298  0
37   0
..  ..
213  1
519  0
432  1
516  1
500  0

[114 rows x 1 columns]

In [ ]:
y_test.values

array([[1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0]])

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
ypred_binary = (ypred >= 0.5).astype(int)
ac=accuracy_score(y_test,ypred_binary)
ac

0.9736842105263158

In [ ]:
cm=confusion_matrix(y_test,ypred_binary)
cm

array([[64,  3],
       [ 0, 47]])